### PR TITLE
New data export schemas endpoint

### PR DESCRIPTION
**Pull request by lavaturtle**
This makes two changes now that we have the `/api/data_exports.json` endpoint:

- Adds documentation for that endpoint endpoint
- Replaces the legacy list of tables and schema information with a list of tables drawn from that endpoint list

In the interests of not making the Bulk Data Data Schemas section unworkably long, we don't display the full information on columns in that section, instead directing users to the API endpoint.

Not included: Updates to the "Controlshift To Redshift Pipeline" section. That will be a later story.

### CODE REVIEW

**Comment by lavaturtle** [comment]
This should not be merged until the new endpoint has been deployed to prod.

**Comment by woodhull** [comment]
Thought about the routes we've created. Would something like `api/bulk_data/schema.json` make more sense?

**Comment by woodhull** [comment]
Looking at how you described it in the docs vs what the api route is caused me to think about it.

**Comment by lavaturtle** [comment]
yeah, that's valid. i'll rename it in agra, then update here

**Comment by woodhull** [comment]
Great! Otherwise this looks perfect.

**Pull request merged**
