### PR TITLE
Documentation for /events create endpoint

### PR DESCRIPTION
**Pull request by lavaturtle**
image

### CODE REVIEW

**Comment by woodhull** [comment]
Questions someone might ask:

- How do I format the location if I want to omit it for a virtual event? Should I just omit the block?
- Is this POST a JSON body?
- Can I update an event after creation?
- ends_at is optional, what happens if ommitted?
- What is an event type? How can I know what valid values are?
- What is a partnership slug? How do I find it?

**Comment by woodhull** [comment]
Maybe some prose providing context might be helpful?

**Comment by lavaturtle** [comment]
I'll add some more explanation, thanks!

**Review by woodhull — APPROVED** [review]
👍

**Comment by lavaturtle** [comment]
OK, I think my changes answer all those questions, except for "what is an event type". I think there's a bit of a gap in our API here -- we should have an API endpoint that lists event types. (Then, the documentation for that endpoint will be the perfect place to explain what they are!)

**Pull request merged**
