### PR TITLE
Added petition ended attributes on JSON response

### PR DESCRIPTION
**Pull request by anero**
screenshot 2018-10-30 15 59 14
screenshot 2018-10-30 15 59 29

### CODE REVIEW

**Comment by lavaturtle** [comment]
Is this correct, given that the `ended` attributes don't seem to appear in the single-petition endpoint?

**Comment by anero** [comment]
Yeah, this isn't accurate, though it's annoying because it seemed the right place to put the new attributes instead of on one of the listing endpoints

**Comment by anero** [comment]
@lavaturtle Updated docs to only refer to new attributes on the endpoints using `shared/petition.jbuilder.json` template

**Review by lavaturtle — APPROVED** [review]
:+1:

**Pull request merged**
